### ISSUE TITLE
[Feature proposal] Support 'attribute group' type in semantic conventions

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/build-tools#123]
Attributes can appear on different signals (metrics, traces, events, links, logs), but we don't have a way to describe attributes without the signal in semantic conventions.
I'd like to have a mechanism, where I'd define attributes separately and then refer to them from spans/links/events definitions.

E.g. in messaging we can have attributes set on links or on spans, maybe events:

```yml
  - id: messaging.message
    prefix: messaging
    type: attribute_group # this is the proposal. We currently use 'span' in cases like this
    brief: 'Semantic convention describing per-message attributes populated on messaging spans or links.'
    attributes:
      - id: message.id
        type: string
        brief: message id
        note:  when sending individual messages, it should be populated on span, otherwise should be populated on links

  - id: messaging.publish
    prefix: messaging
    type: span
    brief:  ...
    attributes:
      - ref: messaging.message.id

  - id: messaging.link
    prefix: messaging
    type: link # out of scope of this proposal
    brief:  ...
    attributes:
      - ref: mesasging.message.id
```

We'd also benefit from it in [span-general.yaml](https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/general.yaml) which essentially describes unrelated groups of attributes, but not a span per se.
