### ISSUE TITLE
Referenced attributes are partially generated in markdown

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/build-tools#136]
Note with possible attribute values (and allowing custom values) is not populated when an attribute is referenced.

E.g. I have 

```yaml
- id: messaging.destination
  prefix: messaging.destination
  brief: 'Semantic convention for attributes that describe messaging destination on broker'
  attributes:
    - id: kind
      type:
        allow_custom_values: true
        members:
          - id: queue
            value: "queue"
            brief: "A message sent to a queue"
          - id: topic
            value: "topic"
            brief: "A message sent to a topic"
```

If I generate md from it using `<!-- semconv messaging.destination-->`,  I'd see an attribute in the table and a note describing possible values:
```
| `messaging.destination.kind` | string | The kind of message destination | `queue` | Recommended |
`messaging.destination.kind` has the following list of well-known values. If one of them applies, then the respective value MUST be used, otherwise a custom value MAY be used.

| Value  | Description |
|---|---|
| `queue` | A message sent to a queue |
| `topic` | A message sent to a topic |
```

Then if I reference this attribute

```yaml
- id: messaging.producer
  prefix: messaging
  type: span
  extends: messaging
  span_kind: producer
  brief: 'Semantic convention for producers of messages sent to a messaging systems.'
  attributes:
    - ref: messaging.destination.kind
      requirement_level:
        conditionally_required: If the message destination is either a `queue` or a `topic`.
```

If I generate md from it using `<!-- semconv messaging.producer-->`,  I'd expect a similar note to be populated, but it's not

https://github.com/open-telemetry/opentelemetry-specification/pull/3214
