### ISSUE TITLE
Support an "integer" enum type?

### ISSUE THREAD

**Issue by toumorokoshi** [open-telemetry/build-tools#19]
In the semantic conventions, [some fields will be strictly integers](https://github.com/open-telemetry/opentelemetry-specification/pull/1156/files#r515520813).  Having an "integer" enum rather than just number for attributes may also enable better linting / enforcement in the auto-generated schemas.

Would it make sense to add this enum?

**Comment by Oberon00** [comment]
Duplicate of #13.

I was talking about supporting integer (or number) enums.

**Comment by toumorokoshi** [comment]
> ~Duplicate of #13.~
> 
> ~I was talking about supporting integer (or number) enums.~
> 
> EDIT: Ah, the description was confusing, with the title it makes sense.

Tried to make the description clearer, but let me know what I can do to better clarify the ask!

**Comment by thisthat** [comment]
The tool already supports it. When an enumeration is declared, the tool infers the type of the enumeration based on the values of its members. Mind that, the tool also verifies that all members of the enumeration have the same type :wink: 
An example of an attribute with an integer enumeration is the following:
```
groups:
  - id: example
    type: span
    brief: 'Example of integer enum'
    prefix: example
    attributes:
		- id: weekdays
		  required: always
		  type:
	          allow_custom_values: false
	          members:
	            - id: MON
	              value: 1
	            - id: TUE
	              value: 2
	            - id: WED
	              value: 3
	            - id: THU
	              value: 4
				- id: FRI
	              value: 5
				- id: SAT
	              value: 6
				- id: SUN
	              value: 7
```
