### ISSUE TITLE
Allow extending enum values when referencing attribute

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/build-tools#192]
Semantic conventions that reference a common attribute with an enum type, should be able to extend/overwrite the list of possible values. 

E.g.

```yaml
- id: http.request.method
  type:
    allow_custom_values: true
    members:
      - id: delete
        value: "DELETE"
        brief: 'DELETE method.'
      - id: get
        value: "GET"
        brief: 'GET method.'
...

- ref: http.request.method
  type:
    allow_custom_values: true
    members:
      - id: purge
        value: "PURGE"
        brief: 'non-standard PURGE method.'
```

currently redeclaring a type is not supported. 

While additional values could be documented in the note, md generation adds another note with possible values according to enum.

Related: https://github.com/open-telemetry/semantic-conventions/pull/205

**Comment by joaopgrassi** [comment]
There's a need for this in https://github.com/open-telemetry/semantic-conventions/pull/258. There's several attributes that are used in different metrics like `hw.status`. From @bertysentry :

> The attributes do have the same meaning across all device types. However, we may want to add an additional values that are specific a type of device. Example: we may want to specify the value charging for the state attribute in the hw.status metric, that is applicable to batteries only (charging).

If these are defined as enums, when `-ref` them in metrics we will need to add more values to it.

**Comment by lmolkova** [comment]
> Would it be better to first decouple the enum definition from the attribute definition and define a top-level "types" section alongside "groups"?

would it mean that the same attribute would have different type for different conventions? Or that we'd need to introduce type inheritance?

**Comment by Oberon00** [comment]
Both, I think 😃

**Comment by lmolkova** [comment]
BTW I believe enums being enums in code generation is a back-compat pain - when value is removed it breaks every lib that used it. 

I think they should be generated as maps instead of enums and then this issue can be resolved without type inheritance or type hell in strongly typed languages.

**Comment by lmolkova** [comment]
(or maybe we can introduce new `map` type so we don't change behavior for existing enum at once)

**Comment by Oberon00** [comment]
> when value is removed it breaks every lib that used it

That will be the case no matter how you implement it. You can at most make it a runtime error instead of a compile time error which would be bad anyways. Removing values from enums is not covered by our stability guarantees I think, but there is no sensible way to implement instrumentations so defensively that they would survive removal of an enum value they actually use without code changes.

**Comment by lmolkova** [comment]
Watch me implement it in the sensible way:  `SemConv.HttpMethods.fromString("PURGE")`

**Comment by lmolkova** [comment]
Another example is `*.system`

E.g. `db.system` has ~50 values.
When we define system-specific semconv, we reference `db.system`  and (if we get rid of not-full tables), we end up listing all 50 in each extension: https://github.com/open-telemetry/semantic-conventions/pull/973

I'd like to be able to do something like

```yaml
- id: db
   ...
   attributes:
    - id: db.system
      type: 
        members: 
        - id: cassandra
        - id: mongodb
        ...

- id: mongodb
   attributes:
    - ref: db.system
      type: 
        members: 
        - ref: mongodb
```

**Comment by ChrsMark** [comment]
Another use-case is the `cpu.state` that we want to introduce.
ref: https://github.com/open-telemetry/semantic-conventions/pull/1026#discussion_r1596882134.

Ideally we want to define the `cpu.state` and then being able to reference it from the `system.*`, `process.*` and `container.*` metrics. However, we would like to have the option to only reference a subset of the enum member in each metricset and also be able to override the value's description/brief so as to be more accurate per metric type.

**Comment by jsuereth** [comment]
Proposal - Yes "refined_type" to define changes to types that won't break semantics.  Refined type only allows differences to be declared.

group A
```
attributes:
- id: http.request.method
  type:
    members:
      -id: POST
```

group B
```
attributes:
- ref: http.request.method
  refined_type:
    restricted_members: 
       - ref: POST
    additional_members:
      - id: purge
        value: "PURGE"
        brief: 'non-standard PURGE method.'
```
