### ISSUE TITLE
Tags should be inherited when extending semconvs

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/build-tools#304]
see https://github.com/open-telemetry/semantic-conventions/pull/698/files#r1525566689

When I do 

```yaml
- id: semconv
  ...
  attributes:
    - id: foo.bar
      ...
      tag: tech-specific

- id: child_senconv
  ...
  extends: semconv
  attributes:
    - ref: foo.bar
```

I expect to inherit tags from `semconv`., but it does not happen today.

I should still be able to override or remove them in the `child_semconv`.
