### ISSUE TITLE
[feature] Build tools/schema should define code-friendly attribute/metric/event/etc names

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/build-tools#323]
See https://github.com/open-telemetry/semantic-conventions/issues/1118 for context

**Comment by jsuereth** [comment]
We are no longer changing how constants are named.  We will either be dropping deprecated names or keeping both with different names in some way.

**Comment by lmolkova** [comment]
Based on the conclusion in https://github.com/open-telemetry/semantic-conventions/issues/1118#issuecomment-2173803006, we need to be able to resolve codegen conflicts at semconv definition time.

E.g.:
- `messaging.client_id` should be marked as dropped in code, see for the details https://github.com/open-telemetry/semantic-conventions/issues/1031#issuecomment-2173887975. The same option could be used for other low-usage attributes
- if we want to preserve an old attribute in the code, we'd need to be able to define a code-friendly constant name in yaml
- the same mechanism could be used to support a wider range of characters (see https://github.com/open-telemetry/semantic-conventions/issues/1124)

Some ideas
1. dropping old
   ```yaml
    attributes:
      - id: foo.bar_baz
        deprecated: "Use `foo.bar.baz` instead"
        code_friendly_name: none # new, optional property, defaults to snake_case(id) 
    ```

2. preserving old and giving new attribute new code const name
    ```yaml
    attributes:
      - id: foo.bar_baz
        deprecated: "Use `foo.bar.baz` instead"

      - id: foo.bar.baz
        code_friendly_name: foo_bar_baz2
```

3. Defining code-friendly name for not supported characters
    ```yaml
      - id: pprof::foo.bar
        code_friendly_name: pprof_foo_bar
    ```
